# Generated by Django 3.2 on 2023-02-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30, unique=True)),
                ('proj_desc', models.TextField()),
                ('proj_qr', models.ImageField(blank=True, null=True, upload_to='')),
                ('screengrab', models.ImageField(blank=True, null=True, upload_to='')),
                ('screengrab_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('languages', models.CharField(max_length=100)),
                ('live_site', models.CharField(default='', max_length=100)),
                ('github_repo', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('friendly_proj_name', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
