# Generated by Django 3.2 on 2024-09-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['project_name']},
        ),
        migrations.AddField(
            model_name='project',
            name='home_display',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
